site_name: Dolce Documentation
nav:
    - index.md
    - quickstart.md
    - configuration.md
    - Notifiers:
          - notifiers/smtp.md
          - notifiers/discord.md
          - notifiers/telegram.md
          - notifiers/slack.md
          - notifiers/mattermost.md
          - notifiers/apprise.md
    - Advanced:
          - advanced/custom-templates.md
          - advanced/reduced-permissions.md
          - advanced/notification-backoff.md

repo_url: https://github.com/dangrie158/dolce
extra_css:
    - css/extra.css
    - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
extra_javascript:
    - js/katex.js
    - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
    - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

theme:
    name: material
    logo: assets/logo_compact.svg
    favicon: assets/logo_compact.png
    features:
        - content.code.annotate
        - content.code.copy

    palette:
        # Palette toggle for automatic mode
        - media: "(prefers-color-scheme)"
          primary: custom
          accent: custom
          toggle:
              icon: material/brightness-auto
              name: Switch to light mode

        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          primary: custom
          accent: custom
          scheme: default
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          primary: custom
          accent: custom
          scheme: slate
          toggle:
              icon: material/brightness-4
              name: Switch to system preference
extra:
    version:
        provider: mike
        default: stable

plugins:
    - mike:
          canonical_version: stable

markdown_extensions:
    - attr_list
    - md_in_html
    - pymdownx.superfences
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - footnotes
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
