name: Bump Version Number
on:
  workflow_dispatch:
    inputs:
      releaseKind:
        description: "Kind of version bump"
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major
        required: true

jobs:
  build:
    name: version bump
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Configure git
        run: |
          git config --global core.symlinks true
          git config --global fetch.parallel 32

      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install deno
        uses: denoland/setup-deno@v1
        with:
          # use a recent version instead of the latest version in case
          # the latest version ever has issues that breaks publishing
          deno-version: v1.30.0

      - name: Run version bump
        run: |
          deno run --allow-read=. --allow-write=. https://deno.land/x/bmp@v0.1.0/cli.ts --${{github.event.inputs.releaseKind}}
          echo "NEW_VERSION=$(deno run --allow-read=. --allow-write=. https://deno.land/x/bmp@v0.1.0/cli.ts --info | grep "Current version:" | cut -c 23-27)" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: "releases/v${{ env.NEW_VERSION }}"
          title: "Bump Version to v${{ env.NEW_VERSION }}"
          body: "This is an automated PR to release Version v${{ env.NEW_VERSION }}"
